# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: get_paper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8/7 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirement
      run: |
        python -m pip install --upgrade pip
        if [ -f requirement.txt ]; then pip install -r requirement.txt; fi
    - name: main_task
      run: |
        sudo cp -p ./chromedriver /usr/bin
        sudo cp -p ./title.txt /usr/bin
        chmod -R 777 /usr/bin/chromedriver
        python ./main.py
        git add title.txt
        git config --global user.name "vail-xjl"
        git config --global user.email "vail_xue@gmail.com"
        git commit -m "Updated title.txt"
        git remote add origin git@github.com:vail-xjl/get_paper.git
        git push origin main
